---

- block:
  - name: Include environment specific vars
    include_vars:
      file: "roles/ytdl/vars/{{ env }}.yml"

#  - name: Install moz hab-butterfly (needed until https://github.com/habitat-sh/habitat/issues/5257 is closed)
#    shell: "hab pkg install mozillareality/hab-butterfly"

  - name: Create work directory
    tempfile:
      state: directory
      suffix: deploy
    register: work_dir

  - name: "Make local target config dir"
    shell: "mkdir -p /hab/user/ytdl/config"

  - name: Write YT-DL config file
    template:
      src: ytdl.toml.j2
      dest: "{{ work_dir.path }}/ytdl.toml"

#  - name: Write DD agent config file
#    template:
#      src: dd-agent.toml.j2
#      dest: "{{ work_dir.path }}/dd-agent.toml"

#  - name: Deploy YT-DL configs
#    shell: "cat {{ work_dir.path }}/ytdl.toml | /hab/pkgs/mozillareality/hab-butterfly/0.39.1/20171118004554/bin/hab-butterfly config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr youtube-dl-api-server.default $(date +%s)"

#  - name: Deploy Datadog Agent configs
#    shell: "cat {{ work_dir.path }}/dd-agent.toml | /hab/pkgs/mozillareality/hab-butterfly/0.39.1/20171118004554/bin/hab-butterfly config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr dd-agent.default $(date +%s)"

  - name: "Copy local config"
    shell: "cp {{ work_dir.path }}/ytdl.toml /hab/user/ytdl/config/user.toml"

  always:
  - name: Remove work directory
    file:
      path: "{{ work_dir.path }}"
      state: absent
